// <auto-generated />
using System;
using ADOSMELHORES.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADOSMELHORES.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20260512135959_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Alocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoFormacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FormadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorHoraNoMomento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FormadorId");

                    b.ToTable("Alocacoes");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFimContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistoCriminal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoFuncionario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasDiscriminator<string>("TipoFuncionario").HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Coordenador", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Funcionarios", t =>
                        {
                            t.Property("Salario")
                                .HasColumnName("Coordenador_Salario");
                        });

                    b.HasDiscriminator().HasValue("Coordenador");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Diretor", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<decimal?>("BonusMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CarroEmpresa")
                        .HasColumnType("bit");

                    b.Property<bool>("IsencaoHorario")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Diretor");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Formador", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<string>("AreaLecionada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CoordenadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDisponibilidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("CoordenadorId");

                    b.HasDiscriminator().HasValue("Formador");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Secretaria", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DiretorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("DiretorId");

                    b.ToTable("Funcionarios", t =>
                        {
                            t.Property("Salario")
                                .HasColumnName("Secretaria_Salario");
                        });

                    b.HasDiscriminator().HasValue("Secretaria");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Alocacao", b =>
                {
                    b.HasOne("ADOSMELHORES.Data.Empresa.Formador", "Formador")
                        .WithMany("Alocacoes")
                        .HasForeignKey("FormadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Formador");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Formador", b =>
                {
                    b.HasOne("ADOSMELHORES.Data.Empresa.Coordenador", "Coordenador")
                        .WithMany("FormadoresAlocados")
                        .HasForeignKey("CoordenadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coordenador");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Secretaria", b =>
                {
                    b.HasOne("ADOSMELHORES.Data.Empresa.Diretor", "DiretorQueReporta")
                        .WithMany("Secretarias")
                        .HasForeignKey("DiretorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DiretorQueReporta");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Coordenador", b =>
                {
                    b.Navigation("FormadoresAlocados");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Diretor", b =>
                {
                    b.Navigation("Secretarias");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Formador", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
