// <auto-generated />
using System;
using ADOSMELHORES.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADOSMELHORES.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20260518194011_dbseeds")]
    partial class dbseeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Alocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoFormacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FormadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormadorId");

                    b.ToTable("Alocacoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            DataFim = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoFormacao = "Curso Intensivo de ASP.NET MVC",
                            FormadorId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFimContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistoCriminal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoFuncionario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasDiscriminator<string>("TipoFuncionario").HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Coordenador", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Funcionarios", t =>
                        {
                            t.Property("Salario")
                                .HasColumnName("Coordenador_Salario");
                        });

                    b.HasDiscriminator().HasValue("Coordenador");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Contacto = "962345678",
                            DataFimContrato = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataRegistoCriminal = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Morada = "",
                            Nome = "Nuno Queirós",
                            Salario = 2200.00m
                        });
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Diretor", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<decimal?>("BonusMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CarroEmpresa")
                        .HasColumnType("bit");

                    b.Property<bool>("IsencaoHorario")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Diretor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Contacto = "912345678",
                            DataFimContrato = new DateTime(2028, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataRegistoCriminal = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Morada = "",
                            Nome = "Mário Oliveira",
                            CarroEmpresa = true,
                            IsencaoHorario = true,
                            Salario = 3500.00m
                        });
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Formador", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<string>("AreaLecionada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CoordenadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDisponibilidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("CoordenadorId");

                    b.HasDiscriminator().HasValue("Formador");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Contacto = "919876543",
                            DataFimContrato = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataRegistoCriminal = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Morada = "",
                            Nome = "Jorge Dias",
                            AreaLecionada = "Programação C#",
                            CoordenadorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoDisponibilidade = 2,
                            ValorHora = 25.50m
                        });
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Secretaria", b =>
                {
                    b.HasBaseType("ADOSMELHORES.Data.Empresa.Funcionario");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DiretorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("DiretorId");

                    b.ToTable("Funcionarios", t =>
                        {
                            t.Property("Salario")
                                .HasColumnName("Secretaria_Salario");
                        });

                    b.HasDiscriminator().HasValue("Secretaria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Contacto = "932345678",
                            DataFimContrato = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataRegistoCriminal = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Morada = "",
                            Nome = "Bruna Buss",
                            Area = "Recursos Humanos",
                            DiretorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Salario = 1100.00m
                        });
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Alocacao", b =>
                {
                    b.HasOne("ADOSMELHORES.Data.Empresa.Formador", "Formador")
                        .WithMany("Alocacoes")
                        .HasForeignKey("FormadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Formador");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Formador", b =>
                {
                    b.HasOne("ADOSMELHORES.Data.Empresa.Coordenador", "Coordenador")
                        .WithMany("FormadoresAlocados")
                        .HasForeignKey("CoordenadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coordenador");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Secretaria", b =>
                {
                    b.HasOne("ADOSMELHORES.Data.Empresa.Diretor", "DiretorQueReporta")
                        .WithMany("Secretarias")
                        .HasForeignKey("DiretorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DiretorQueReporta");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Coordenador", b =>
                {
                    b.Navigation("FormadoresAlocados");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Diretor", b =>
                {
                    b.Navigation("Secretarias");
                });

            modelBuilder.Entity("ADOSMELHORES.Data.Empresa.Formador", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
